a=['China', 'Denmark', 'Netherlands', 'USA', 'Finland', 'Norway',
       'Romania', 'Estonia', 'France', 'Morocco', 'Spain', 'Egypt',
       'Iran', 'Bulgaria', 'Chad', 'Sudan', 'Russia', 'Argentina', 'Cuba',
       'Belarus', 'Greece', 'Cameroon', 'Turkey', 'Chile', 'Mexico',
       'Italy', 'Nicaragua', 'Hungary', 'Nigeria', 'Algeria', 'Kuwait',
       'Bahrain', 'Pakistan', 'Iraq', 'Syria', 'Lebanon', 'Qatar',
       'Malaysia', 'Azerbaijan', 'Germany', 'Canada', 'Ireland',
       'South Africa', 'Eritrea', 'Tanzania', 'Jordan', 'Tunisia',
       'Libya', 'Belgium', 'Australia', 'Djibouti', 'Palestine',
       'Comoros', 'Kazakhstan', 'Brunei', 'India', 'Saudi Arabia',
       'Maldives', 'Ethiopia', 'United Arab Emirates', 'Yemen',
       'Indonesia', 'Philippines', 'Uzbekistan', 'Kyrgyzstan',
       'Tajikistan', 'Japan', 'Republic of Congo', 'Switzerland',
       'Brazil', 'Monaco', 'Israel', 'Uruguay', 'Sweden',
       'Virgin Islands, US', 'Sri Lanka', 'Armenia', 'Ivory Coast',
       'Kenya', 'Benin', 'Ukraine', 'UK', 'Ghana', 'Somalia', 'Latvia',
       'Niger', 'Mali', 'Afghanistan', 'Poland', 'Costa Rica', 'Panama',
       'Georgia', 'Slovenia', 'Croatia', 'Guyana', 'New Zealand',
       'Portugal', 'Paraguay', 'Angola', 'Venezuela', 'Colombia',
       'Bangladesh', 'Peru', 'El Salvador', 'Uganda', 'Honduras',
       'Ecuador', 'Turkmenistan', 'Mauritius', 'Seychelles',
       'Czech Republic', 'Luxembourg', 'Mauritania', 'Saint Kitts',
       'Trinidad', 'Dominican Republic', 'Saint Vincent', 'Puerto Rico',
       'Jamaica', 'Liberia', 'Suriname', 'Nepal', 'Mongolia', 'Austria',
       'Palau', 'Lithuania', 'Togo', 'Namibia', 'Curacao', 'Iceland',
       'American Samoa', 'Samoa', 'Rwanda', 'Dominica', 'Haiti', 'Malta',
       'Cyprus', 'Guinea', 'Belize', 'South Korea', 'Thailand', 'Bermuda',
       'Serbia', 'Sierra Leone', 'Papua New Guinea',
       'Individual Olympic Athletes', 'Oman', 'Fiji', 'Vanuatu',
       'Moldova', 'Bahamas', 'Guatemala', 'Virgin Islands, British',
       'Mozambique', 'Central African Republic', 'Madagascar',
       'Bosnia and Herzegovina', 'Guam', 'Cayman Islands', 'Slovakia',
       'Barbados', 'Guinea-Bissau', 'Timor-Leste',
       'Democratic Republic of the Congo', 'Gabon', 'San Marino', 'Laos',
       'Botswana', 'Cambodia', 'North Korea', 'Solomon Islands',
       'Senegal', 'Cape Verde', 'Equatorial Guinea', 'Boliva', 'Andorra',
       'Antigua', 'Zimbabwe', 'Grenada', 'Saint Lucia', 'Micronesia',
       'Myanmar', 'Malawi', 'Zambia', 'Taiwan', 'Sao Tome and Principe',
       'Macedonia', 'Tonga', 'Liechtenstein', 'Montenegro', 'Gambia',
       'Cook Islands', 'Albania', 'Swaziland', 'Burkina Faso', 'Burundi',
       'Aruba', 'Nauru', 'Vietnam', 'Bhutan', 'Marshall Islands',
       'Kiribati', 'Kosovo', 'South Sudan', 'Lesotho']

b=['Denmark', 'Finland', 'Norway', 'Netherlands', 'France', 'Italy',
       'Spain', 'Azerbaijan', 'Russia', 'Belarus', 'Cameroon', 'USA',
       'Hungary', 'Greece', 'Australia', 'Iran', 'Canada', 'Pakistan',
       'Uzbekistan', 'Tajikistan', 'Japan', 'Ethiopia', 'Switzerland',
       'Germany', 'Sweden', 'South Africa', 'Turkey', 'Bulgaria', 'Egypt',
       'UK', 'Jordan', 'Romania', 'Puerto Rico', 'Mexico', 'Ghana',
       'Morocco', 'New Zealand', 'Argentina', 'Cuba', 'Uruguay', 'Poland',
       'Czech Republic', 'Nigeria', 'Brazil', 'Austria', 'Lithuania',
       'Indonesia', 'Chile', 'Ukraine', 'Uganda', 'Syria', 'Qatar',
       'Kuwait', 'Individual Olympic Athletes', 'Saudi Arabia',
       'United Arab Emirates', 'Croatia', 'Armenia', 'Serbia', 'Niger',
       'India', 'Belgium', 'Algeria', 'Jamaica', 'Trinidad', 'Colombia',
       'Luxembourg', 'Botswana', 'Tunisia', 'South Korea', 'North Korea',
       'China', 'Guyana', 'Israel', 'Kazakhstan', 'Georgia', 'Kenya',
       'Iceland', 'Haiti', 'Malaysia', 'Iraq', 'Slovakia', 'Bahamas',
       'Paraguay', 'Montenegro', 'Ireland', 'Portugal', 'Guatemala',
       'Tanzania', 'Lebanon', 'Kyrgyzstan', 'Latvia', 'Curacao',
       'Venezuela', 'Thailand', 'Togo', 'Peru', 'Estonia', 'Slovenia',
       'Nepal', 'Taiwan', 'Zimbabwe', 'Mongolia', 'Moldova',
       'Ivory Coast', 'Fiji', 'Senegal', 'Dominican Republic',
       'Philippines', 'Namibia', 'Liechtenstein', 'Bermuda',
       'Vietnam', 'Virgin Islands, US', 'Macedonia', 'Sudan', 'Bahrain',
       'Grenada', 'Sri Lanka', 'Mauritius', 'Kosovo', 'Cyprus', 'Panama',
       'Zambia', 'Monaco', 'Mozambique', 'Suriname', 'Afghanistan',
       'Burundi', 'Gabon', 'Ecuador', 'Costa Rica', 'Djibouti', 'Eritrea',
       'Barbados', 'Tonga']

d=[]
c=0
for i in a:
    if i not in b:
        d.append(i)
        c+=1
f=['Albania', 'American Samoa', 'Andorra', 'Angola', 'Antigua', 'Aruba', 'Bangladesh',
   'Belize', 'Benin', 'Bhutan', 'Boliva', 'Bosnia and Herzegovina', 'Brunei', 'Burkina Faso',
   'Cambodia', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Comoros',
   'Cook Islands', 'Democratic Republic of the Congo', 'Dominica', 'El Salvador',
   'Equatorial Guinea', 'Gambia', 'Guam', 'Guinea', 'Guinea-Bissau', 'Honduras', 'Kiribati',
   'Laos', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Maldives', 'Mali', 'Malta',
   'Marshall Islands', 'Mauritania', 'Micronesia', 'Myanmar', 'Nauru', 'Nicaragua', 'Oman',
   'Palau', 'Palestine', 'Papua New Guinea', 'Republic of Congo', 'Rwanda', 'Saint Kitts',
   'Saint Lucia', 'Saint Vincent', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Seychelles',
   'Sierra Leone', 'Solomon Islands', 'Somalia', 'South Sudan', 'Swaziland', 'Timor-Leste',
   'Turkmenistan', 'Vanuatu', 'Virgin Islands, British', 'Yemen']

d=sorted(d)
print(d)
print(c)